-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 11:10:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema isound
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema isound
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isound` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `isound` ;

-- -----------------------------------------------------
-- Table `isound`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isound`.`users` (
  `user_id` VARCHAR(40) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(50) NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `isound`.`user_playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isound`.`user_playlists` (
  `playlist_id` VARCHAR(40) NOT NULL,
  `playlist_name` VARCHAR(100) NOT NULL,
  `playlist_status` TINYINT(1) NULL DEFAULT NULL,
  `playlist_image` VARCHAR(255) NULL DEFAULT NULL,
  `playlist_description` TEXT NULL DEFAULT NULL,
  `user_id` VARCHAR(40) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`playlist_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_playlists_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `isound`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `isound`.`playlist_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isound`.`playlist_details` (
  `playlist_id` VARCHAR(40) NOT NULL,
  `media_id` VARCHAR(20) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  INDEX `playlist_id` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `playlist_details_ibfk_1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `isound`.`user_playlists` (`playlist_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `isound`.`user_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isound`.`user_like` (
  `user_id` VARCHAR(40) NOT NULL,
  `media_id` VARCHAR(20) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_like_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `isound`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
